name: hotkey_manager_interface
description: A common platform interface for the hotkey_manager plugin.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8
  uni_platform: ^0.1.3
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.1
